spring.application.name=first-task
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/intern_demo}
spring.datasource.username=${DB_USERNAME:ragib}
spring.datasource.password=${DB_PASSWORD:Asdf1234}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true